In [1]:
import pandas as pd
import numpy as np

In [8]:
s1 = pd.Series(data=[10,20,30,40,50], name='Numbers')
s1

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64

In [3]:
s2 = pd.Series(data=[100,200,300,400,500])
s2

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [11]:
s3 = pd.Series(data=[1000,2000,3000,4000,5000],index=list('ABCDE'))
s3

A    1000
B    2000
C    3000
D    4000
E    5000
dtype: int64

In [5]:
df = pd.DataFrame({'C1':s1, 'C2':s2, 'C3':[11, 22, 33, 44, 55]})
df

   C1   C2  C3
0  10  100  11
1  20  200  22
2  30  300  33
3  40  400  44
4  50  500  55

In [6]:
df = pd.DataFrame(data=np.random.randint(1,100,size=(1000,5)), columns=list('abcde'))       #(start, end, size=(rows, series))
df

      a   b   c   d   e
0    10  32  10  87  66
1    86  64  11  76  76
2    24  63  75  77  59
3    47   8  13  31  55
4    49   8  23  49  20
..   ..  ..  ..  ..  ..
995   6   4  72  85  12
996  21  31  97  75  98
997  37  30  97  48  86
998  26  19  11  35  58
999  40  71  64  47  20

[1000 rows x 5 columns]

In [7]:
dataset = pd.read_csv("/week1/w1_s3/Session 3/DATASETS/DATASETS/Car.csv")
dataset

FileNotFoundError: [Errno 2] No such file or directory: '/week1/w1_s3/Session 3/DATASETS/DATASETS/Car.csv'

In [ ]:
dataset.info()

In [ ]:
dataset.head()

In [ ]:
dataset.tail()

In [ ]:
dataset.Car.value_counts()              # Tells the total count of the particular value

In [ ]:
dataset.rename(columns={'Car':'Target'})    # Temporary change the name

In [ ]:
dataset

In [ ]:
dataset.rename(columns={'Car':'Target'},inplace=True)       # Permanently change the name
dataset

In [ ]:
dataset.columns

In [ ]:
dataset[['Age','Target']]

In [ ]:
dataset.loc[50]

In [ ]:
dataset.loc[50:60]

In [ ]:
dataset[(dataset['Income'] > 100000)]

In [ ]:
import pandas as pd
example = pd.read_csv('/w1_s3\\Session 3\\DATASETS\\DATASETS\\abc.csv')
example

In [ ]:
example['price'].notnull()      # returns is the value is null or not in true or false output

In [ ]:
example[example['price'].isnull()]

In [ ]:
example['price'].fillna(example['price'].max())             # NAN is filled with max value from the price series temporary

In [ ]:
example['price'] = example['price'].fillna(example['price'].std())          # Fill the values using standard deviation
example

In [ ]:
example['price'] = example['price'].fillna(example['price'].min())
example

In [ ]:
example['price'] = example['price'].fillna(example['price'].max())
example

In [ ]:
example['price'] = example['price'].fillna(example['price'].mean())
example

In [ ]:
df.drop(['b'],axis='columns')       # Temporary drop

In [ ]:
df

In [ ]:
df.drop(['b'],axis='columns',inplace=True)      # Permanent
df

In [ ]:
data1 = pd.DataFrame(data=np.random.randint(1,100,size=(100,4)), columns=list('abcd'))

In [ ]:
data2 = pd.DataFrame(data=np.random.randint(1,100,size=(100,3)), columns=list('xyz'))

In [ ]:
data1

In [ ]:
data2

In [ ]:
data1.append(data2)             # DataFrame doesnt contains append method

In [ ]:
data3 = pd.DataFrame(data=np.random.randint(1,100,size=(100,3)), columns=list('abc'))

In [ ]:
data4 = pd.DataFrame(data=np.random.randint(1,100,size=(100,3)), columns=list('ayz'))

In [ ]:
data3.merge(data4, on='a')

In [ ]:
11 50 74 data3
11 54 36 data4